package(default_visibility=["//visibility:public"])
load("@npm_bazel_typescript//:index.bzl", "ts_library")

ts_library(
    name = "test",
    srcs = ["test.ts"],
    deps = [],
)

ts_library(
  name = "common",
  srcs = ["common.ts"],
  deps = [],
)
